# Generated by Django 5.0.6 on 2024-05-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_userprofile_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="address",
        ),
        migrations.RemoveField(
            model_name="property",
            name="city",
        ),
        migrations.RemoveField(
            model_name="property",
            name="nearby",
        ),
        migrations.RemoveField(
            model_name="property",
            name="state",
        ),
        migrations.RemoveField(
            model_name="property",
            name="zip_code",
        ),
    ]
